# Generated by Django 4.1.1 on 2022-09-27 01:12

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animation",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("series_id", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=255)),
                ("content", models.CharField(max_length=500)),
                ("content_rating", models.CharField(max_length=20)),
                ("genres", djongo.models.fields.JSONField()),
                ("tags", djongo.models.fields.JSONField()),
                ("highlight_video", djongo.models.fields.JSONField()),
                ("images", djongo.models.fields.JSONField()),
                ("avg_rating", models.FloatField(default=0)),
                ("air_year_quarter", models.CharField(max_length=50)),
                ("distributed_air_time", djongo.models.fields.JSONField()),
                ("author", djongo.models.fields.JSONField()),
                ("production", models.CharField(max_length=20)),
                ("is_adult", models.BooleanField()),
                ("is_ending", models.BooleanField()),
            ],
            options={"db_table": "ani_info",},
        ),
    ]
