# Generated by Django 4.1.1 on 2022-10-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("profile", models.IntegerField()),
                ("score", models.FloatField()),
                ("content", models.CharField(max_length=1000)),
            ],
        ),
    ]
