# Generated by Django 4.1.1 on 2022-10-01 18:04

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("animations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("feature", djongo.models.fields.JSONField()),
                ("feat_str", models.CharField(max_length=1000)),
                ("series_id", models.CharField(max_length=10)),
                ("related", djongo.models.fields.JSONField()),
            ],
            options={"db_table": "ani_feature",},
        ),
    ]
