# Generated by Django 4.1.1 on 2022-10-01 22:27

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("animations", "0002_feature"),
    ]

    operations = [
        migrations.RemoveField(model_name="history", name="history",),
        migrations.AddField(
            model_name="history",
            name="recommended",
            field=djongo.models.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="review", name="animation", field=models.IntegerField(default=0),
        ),
    ]
